# Generated by Django 5.1.1 on 2024-09-22 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_record_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unit'),
        ),
    ]
