# Generated by Django 5.1.1 on 2024-09-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_percentage_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('region', 'Вилоят'), ('city', 'Шахар'), ('mosque', 'Масжид')], default='region', max_length=10),
        ),
    ]
