# Generated by Django 5.1.1 on 2024-09-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_category_core_catego_name_6ef604_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='unit',
        ),
    ]
