# Generated by Django 5.1.1 on 2024-09-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_record_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'СуперАдмин'), ('region_admin', 'Админ Региона'), ('city_admin', 'Админ Города'), ('mosque_admin', 'Админ Мечети')], default='mosque_admin', max_length=20, null=True),
        ),
    ]
