# Generated by Django 5.1.1 on 2024-09-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_place_place_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
