# Generated by Django 5.1.1 on 2024-09-30 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_category_created_at_alter_place_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='updated_by',
        ),
    ]
